server:
  port: 8001
spring:
  application:
    name: datetime-app
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"

